---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(knitr)
library(kableExtra)

```
```{r table codebook, results='asis', echo=FALSE}

# Vector of variable names
varnames1 <- c("row_id",
"article_id",
"article_id_recoded",
"journal_id",
"url_article",
"url_data",
"year",
"author",
"study",
"study_recoded",
"empirical",
"compare_group",
"type_group",
"name_group",
"scale",
"reference",
"psychometric",
"consistency",
"reflective",
"name_scale	",
"type_scale",
"measure_scale",
"width_scale",
"width_scale_recoded",
"no_items",
"power",
"n_rep",
"n1_rep",
"n2_rep",
"n3_rep",
"n4_rep",
"n5_rep",
"rel_rep",
"rel1_rep",
"rel2_rep",
"rel3_rep",
"rel4_rep",
"rel5_rep",
"mitest_rep",
"mimethod_rep",
"miresult_rep",
"milevel_rep",
"comments",
"cat_group",
"open_data",
"open_scale",
"open_group",
"n_res",
"n1_res",
"n2_res",
"n3_res",
"n4_res",
"n5_res",
"mitest_step2",
"miresult_step2",
"milevel_step2",
"reproduced_step2",
"comments_step2",
"mitest_step3",
"miresult_step3",
"milevel_step3",
"comments_step3",
"open_data",
"open_scale",
"open_group",
"n_res",
"n1_res",
"n2_res",
"n3_res",
"n4_res",
"n5_res",
"mitest_step4",
"miresult_step4",
"milevel_step4",
"config_assumed",
"comments_step4",
"parallel",
"f_total",
"f_group",
"est_rel")

# Vector of variable descriptions
vardes1 <- c("Row ID",
"Article ID",
"Article ID recoded",
"Journal ID	",
"URL to the article",
"URL to the data file",
"Year the article was published",
"First author of the article",
"Number of study within the paper",
"Number of study within the paper recoded",
"Does the article contain empirical human data?",
"Are group or time comparisons conducted in the article?",
"Are groups constructed for the study or do they already exist?",
"Name of the group being compared",
"Is a scale measured in the article, that is compared between groups?",
"Was a reference to a previous (validation) study reported?",
"Are psychometric analysis reported?",
"Is internal consistency reported?",
"Is the scale reflective?",
"Name of the scale",
"Scale type",
"Level of measurement for the scale",
"Width of the scale",
"Width of the scale recoded",
"Number of items in the scale",
"What is the estimate of statistical power reported for the test used to make the comparison?",
"Reported total sample size",
"Reported total sample size group 1",
"Reported total sample size group 2",
"Reported total sample size group 3",
"Reported total sample size group 4",
"Reported total sample size group 5",
"Reported reliability estimate for the scale",
"Reported reliability estimate for the scale in group 1",
"Reported reliability estimate for the scale in group 2",
"Reported reliability estimate for the scale in group 3",
"Reported reliability estimate for the scale in group 4",
"Reported reliability estimate for the scale in group 5",
"Does the article report on measurement invariance of a MI check with regard to the measured scale?",
"Reported method of measurement invariance check used",
"Scale reported to be measurement invariant?",
"Reported level of measurement invariance that held",
"Comments related to step 1",
"Type group categorized into one of three categories",
"Can we open the data file(s) of the scale group comparisons?",
"Can we construct a scale from the data?",
"Can we construct groups from the data?",
"Reproduced total sample size",
"Reproduced total sample size group 1",
"Reproduced total sample size group 2",
"Reproduced total sample size group 3",
"Reproduced total sample size group 4",
"Reproduced total sample size group 5",
"Are we able to test for measurement invariance?",
"Do our results show there is measurement invariance?",
"Level of measurement invariance that held",
"Could we reproduce the reported results on measurement invariance?",
"Comments related to step 2",
"Are we able to test for measurement invariance?",
"Do our results show there is measurement invariance?",
"Level of measurement invariance that held",
"Comments related to step 3",
"Can we open the data file(s) of the scale group comparisons?",
"Can we construct a scale from the data?",
"Can we construct groups from the data?",
"Estimated total sample size",
"Estimated total sample size group 1",
"Estimated total sample size group 2",
"Estimated total sample size group 3",
"Estimated total sample size group 4",
"Estimated total sample size group 5",
"Are we able to test for measurement invariance?",
"Do our results show there is measurement invariance?",
"Level of measurement invariance that held",
"Do we assume configural invariance because scale has three items?",
"Comments related to step 3",
"Are we able to perform Parallel Analysis?",
"Number of factors estimated through Parallel Analysis (entire sample)",
"Number of factors estimated through Parallel Analysis (per group)",
"Estimated reliability (Cronbach's alpha) for the entire sample")

# Vector of additional info (e.g., measurements)
info1  <-  c("",
"",
"Recoded Article IDs, now ordered from 1 to 426",
"0 = PLOSONE, 1 = PS",
"",
"",
"",
"",
"",
"Study number recoded into ordered integers, e.g., studies 1a and 1b become study 1 and 2",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = existing group (e.g., country), 1 = new group (e.g., treatment group)",
"",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"",
"0 = existing or validated scale, 1 = ad hoc scale",
"0 = dichotomous (0 to 1), 1 = ordinal (from 3 to 5 categories), 2 = continous (more than 5 categories)",
"E.g., 1-7",
"Width scale recoded to the number of response answers, e.g., 7 for a seven-point scale",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"0 = no, 1 = yes",
"1 = scale-based (includes CFA, CCFA, MIMIC, LCFA), 2 = item-based (IRT, LRT, logistic regression), 3 = other (in comments), NA = not applicable",
"0 = no, 1 = yes",
"0 = none, 1 = configural, 2 = metric/non-uniform/slope/weak, 3 = scalar/uniform/intercept/strong, 4 = residual/strict, 5 = partial invariance, 99 = other",
"",
"dem = comparison between demographic groups, exp_misc = comparison between ad hoc constructed groups, exp_time = comparisons over time",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"",
"",
"",
"",
"",
"",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = none, 1 = configural, 2 = metric/non-uniform/slope/weak, 3 = scalar/uniform/intercept/strong, 4 = residual/strict, 5 = partial invariance",
"0 = no, 1 = yes",
"",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = none, 1 = configural, 2 = metric/non-uniform/slope/weak, 3 = scalar/uniform/intercept/strong, 4 = residual/strict, 5 = partial invariance",
"",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"",
"",
"",
"",
"",
"",
"0 = no, 1 = yes",
"0 = no, 1 = yes",
"0 = none, 1 = configural, 2 = metric/non-uniform/slope/weak, 3 = scalar/uniform/intercept/strong, 4 = residual/strict, 5 = partial invariance",
"0 = no, 1 = yes",
"",
"0 = no, 1 = yes",
"",
"",
"")

# Combine vectors into a table
tabledf1 <- cbind(varnames1,vardes1,info1)
colnames(tabledf1) <- c("Variable name", "Variable label", "Additional information") # column names

# Make table
kable(tabledf1, caption='Variables included in the codebooks.', booktabs=T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = TRUE) %>%
                column_spec(1, width = "8em") %>% 
                column_spec(2, width = "35em") %>% 
                column_spec(3, width = "35em") %>% 
                pack_rows("Step 1 variables (reporting)", 1, 43) %>% 
                pack_rows("Step 2 + 3 variables (reproducibility)", 44, 62) %>% 
                pack_rows("Step 4 variables (reuse)", 63, 80)

```

